name: Engelleri kaldır
on:
  schedule:
    - cron: '0 */2 * * *'  # Her 6 saatte bir çalıştırır
  workflow_dispatch:  # Manuel çalıştırma imkanı

jobs:
  update-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Add timestamp to Dockerfile
        run: |
          NOWDATE=`date "+%Y-%m-%d %H:%M:%S"`
          echo "RUN echo 'Rebuild $NOWDATE' >> /app/rebuild.log" >> Dockerfile
          
      - name: Commit and push the update
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add Dockerfile
          git commit -m "♻️ otomatik rebuild hf $NOWDATE"
          git push -f https://oauth2:HUGGINGFACE_TOKEN@huggingface.co/spaces/$HUGGINGFACE_SPACE_NAME main

        env:
          HUGGINGFACE_SPACE_NAME: ${{ vars.HUGGINGFACE_SPACE_NAME }}
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
