name: 📺🔄 LaLaLa

on:
  push:
    paths:
      - "dl/dl-daddyliveall.m3u"
      - "dl/daddyliveevents.m3u"
  workflow_dispatch:  # Manuel çalıştırma seçeneği

jobs:
  update_m3u:
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu çek
      uses: actions/checkout@v4

    - name: Python'u kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Bağımlılıkları yükle
      run: pip install requests

    # - name: Stream URL’lerini temizle ve Base64 kodlarını decode et #
    #  run: python .github/scripts/lalala.py #

    - name: Güncellenmiş dosyayı repoya yükle
      env:
        GITHUB_TOKEN: ${{ secrets.LATTE_PAT }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add -A  # Tüm dosyaları ekle
        git commit --allow-empty -m "♻ Otomatik güncellenmiş M3U listesi"
        git push origin main
    
    - name: Temizle Gitsin
      run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git checkout --orphan new_main
          git add -A
          git commit -m "♻ Listeler güncellendi 🧹 Geçmişe paydos!"
          
          git branch -D main
          git branch -m main
          
          git push --force --set-upstream origin main        
